# **Data Collection Notebook**

## Objectives

* Fetch data from Kaggle, via storage on local computer, and save it as raw data.
* Inspect the data and save it under outputs/datasets/collection

## Inputs

*   The inputs/datasets/raw/Airplane_Complete_Imputation.csv downloaded from Kaggle and uploaded to gitpod workspace via local computer.

## Outputs

* Generate Dataset: outputs/datasets/collection/airplane_performance_study.csv

## Additional Comments

Method to download data directly from Kaggle to the notebook with an authentication token (Kaggle JSON file) gave a "403 - Forbidden".

---

# Change working directory

We need to change the working directory from its current folder to its parent folder
* Access the current directory with os.getcwd()

In [11]:
import os
current_dir = os.getcwd()
current_dir

'/workspace/data-driven-design'

Make the parent of the current directory the new current directory.
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [12]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [13]:
current_dir = os.getcwd()
current_dir

'/workspace'

---

# Install python packages in the notebooks

In [14]:
pip install --upgrade pip

Requirement already satisfied: pip in ./.pip-modules/lib/python3.10/site-packages (25.0.1)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import subprocess

# Read the packages from requirements.txt
req_file = "/workspace/data-driven-design/requirements.txt"
with open(req_file, "r") as f:
    packages = [line.strip().split("==")[0] for line in f if line.strip() and not line.startswith("#")]

# Uninstall all packages
subprocess.run(["pip", "uninstall", "-y"] + packages)

Found existing installation: feature-engine 1.6.2
Uninstalling feature-engine-1.6.2:
  Successfully uninstalled feature-engine-1.6.2
Found existing installation: setuptools 75.8.2
Uninstalling setuptools-75.8.2:
  Successfully uninstalled setuptools-75.8.2
Found existing installation: wheel 0.45.1
Uninstalling wheel-0.45.1:
  Successfully uninstalled wheel-0.45.1
Found existing installation: streamlit 1.42.2
Uninstalling streamlit-1.42.2:
  Successfully uninstalled streamlit-1.42.2
Found existing installation: plotly 5.16.1
Uninstalling plotly-5.16.1:
  Successfully uninstalled plotly-5.16.1
Found existing installation: numpy 2.2.3
Uninstalling numpy-2.2.3:
  Successfully uninstalled numpy-2.2.3
Found existing installation: pandas 2.2.3
Uninstalling pandas-2.2.3:
  Successfully uninstalled pandas-2.2.3
Found existing installation: seaborn 0.11.2
Uninstalling seaborn-0.11.2:
  Successfully uninstalled seaborn-0.11.2
Found existing installation: matplotlib 3.7.0
Uninstalling matplotlib-3.7.0:
  Successfully uninstalled matplotlib-3.7.0
Found existing installation: scikit-learn 1.2.2
Uninstalling scikit-learn-1.2.2:
  Successfully uninstalled scikit-learn-1.2.2

CompletedProcess(args=['pip', 'uninstall', '-y', 'feature-engine>=1.2.0', 'setuptools>=70.3.0', 'wheel>=0.45.1', 'streamlit>=1.14.0', 'plotly>=5.16.0,<5.17.0', 'numpy>=1.20.0', 'pandas>=1.5.3', 'seaborn', 'matplotlib', 'scikit-learn'], returncode=0)

In [20]:
subprocess.run(["pip", "cache", "purge"])

Files removed: 0 (0 bytes)

WARNING: No matching packages

CompletedProcess(args=['pip', 'cache', 'purge'], returncode=0)

In [21]:
subprocess.run(["pip", "install", "--no-cache-dir", "-r", req_file])

Collecting feature-engine>=1.2.0 (from -r /workspace/data-driven-design/requirements.txt (line 1))
  Downloading feature_engine-1.8.3-py2.py3-none-any.whl.metadata (9.9 kB)
Collecting setuptools>=70.3.0 (from -r /workspace/data-driven-design/requirements.txt (line 2))
  Downloading setuptools-75.8.2-py3-none-any.whl.metadata (6.7 kB)
Collecting wheel>=0.45.1 (from -r /workspace/data-driven-design/requirements.txt (line 3))
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Collecting streamlit>=1.14.0 (from -r /workspace/data-driven-design/requirements.txt (line 4))
  Downloading streamlit-1.42.2-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting plotly<5.17.0,>=5.16.0 (from -r /workspace/data-driven-design/requirements.txt (line 5))
  Downloading plotly-5.16.1-py2.py3-none-any.whl.metadata (7.0 kB)
Collecting numpy>=1.20.0 (from -r /workspace/data-driven-design/requirements.txt (line 6))
  Downloading numpy-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting pandas>=1.5.3 (from -r /workspace/data-driven-design/requirements.txt (line 7))
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting seaborn==0.11.2 (from -r /workspace/data-driven-design/requirements.txt (line 8))
  Downloading seaborn-0.11.2-py3-none-any.whl.metadata (2.3 kB)
Collecting matplotlib==3.7.0 (from -r /workspace/data-driven-design/requirements.txt (line 9))
  Downloading matplotlib-3.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting scikit-learn==1.2.2 (from -r /workspace/data-driven-design/requirements.txt (line 10))
  Downloading scikit_learn-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy>=1.0 in ./.pip-modules/lib/python3.10/site-packages (from seaborn==0.11.2->-r /workspace/data-driven-design/requirements.txt (line 8)) (1.15.2)
Requirement already satisfied: contourpy>=1.0.1 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (4.56.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (1.4.8)
Requirement already satisfied: packaging>=20.0 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (24.2)
Requirement already satisfied: pillow>=6.2.0 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (2.9.0.post0)
Requirement already satisfied: joblib>=1.1.1 in ./.pip-modules/lib/python3.10/site-packages (from scikit-learn==1.2.2->-r /workspace/data-driven-design/requirements.txt (line 10)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.pip-modules/lib/python3.10/site-packages (from scikit-learn==1.2.2->-r /workspace/data-driven-design/requirements.txt (line 10)) (3.5.0)
INFO: pip is looking at multiple versions of feature-engine to determine which version is compatible with other requirements. This could take a while.
Collecting feature-engine>=1.2.0 (from -r /workspace/data-driven-design/requirements.txt (line 1))
  Downloading feature_engine-1.8.2-py2.py3-none-any.whl.metadata (9.9 kB)
  Downloading feature_engine-1.8.1-py2.py3-none-any.whl.metadata (9.8 kB)
  Downloading feature_engine-1.8.0-py2.py3-none-any.whl.metadata (9.8 kB)
  Downloading feature_engine-1.7.0-py2.py3-none-any.whl.metadata (9.8 kB)
  Downloading feature_engine-1.6.2-py2.py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: statsmodels>=0.11.1 in ./.pip-modules/lib/python3.10/site-packages (from feature-engine>=1.2.0->-r /workspace/data-driven-design/requirements.txt (line 1)) (0.14.4)
Requirement already satisfied: altair<6,>=4.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (5.5.0)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (1.4)
Requirement already satisfied: cachetools<6,>=4.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (8.1.8)
Requirement already satisfied: protobuf<6,>=3.20 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (19.0.1)
Requirement already satisfied: requests<3,>=2.27 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (13.9.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.1.44)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (6.4.2)
Requirement already satisfied: pytz>=2020.1 in ./.pip-modules/lib/python3.10/site-packages (from pandas>=1.5.3->-r /workspace/data-driven-design/requirements.txt (line 7)) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in ./.pip-modules/lib/python3.10/site-packages (from pandas>=1.5.3->-r /workspace/data-driven-design/requirements.txt (line 7)) (2025.1)
Requirement already satisfied: jinja2 in ./.pip-modules/lib/python3.10/site-packages (from altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.1.5)
Requirement already satisfied: jsonschema>=3.0 in ./.pip-modules/lib/python3.10/site-packages (from altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in ./.pip-modules/lib/python3.10/site-packages (from altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (1.29.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./.pip-modules/lib/python3.10/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (4.0.12)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.pip-modules/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in ./.pip-modules/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.pip-modules/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.pip-modules/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2025.1.31)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.pip-modules/lib/python3.10/site-packages (from rich<14,>=10.14.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.pip-modules/lib/python3.10/site-packages (from rich<14,>=10.14.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2.19.1)
Requirement already satisfied: patsy>=0.5.6 in ./.pip-modules/lib/python3.10/site-packages (from statsmodels>=0.11.1->feature-engine>=1.2.0->-r /workspace/data-driven-design/requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: smmap<6,>=3.0.1 in ./.pip-modules/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.pip-modules/lib/python3.10/site-packages (from jinja2->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in ./.pip-modules/lib/python3.10/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (25.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.pip-modules/lib/python3.10/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in ./.pip-modules/lib/python3.10/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in ./.pip-modules/lib/python3.10/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.23.1)
Requirement already satisfied: mdurl~=0.1 in ./.pip-modules/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.1.2)
Downloading seaborn-0.11.2-py3-none-any.whl (292 kB)
Downloading matplotlib-3.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 256.3 MB/s eta 0:00:00
Downloading scikit_learn-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 422.9 MB/s eta 0:00:00
Downloading feature_engine-1.6.2-py2.py3-none-any.whl (328 kB)
Downloading setuptools-75.8.2-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 538.0 MB/s eta 0:00:00
Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
Downloading streamlit-1.42.2-py2.py3-none-any.whl (9.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 92.4 MB/s eta 0:00:00
Downloading plotly-5.16.1-py2.py3-none-any.whl (15.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 287.0 MB/s eta 0:00:00
Downloading numpy-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 424.0 MB/s eta 0:00:00
Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 345.7 MB/s eta 0:00:00
Installing collected packages: wheel, setuptools, plotly, numpy, pandas, scikit-learn, matplotlib, seaborn, feature-engine, streamlit
Successfully installed feature-engine-1.6.2 matplotlib-3.7.0 numpy-2.2.3 pandas-2.2.3 plotly-5.16.1 scikit-learn-1.2.2 seaborn-0.11.2 setuptools-75.8.2 streamlit-1.42.2 wheel-0.45.1

CompletedProcess(args=['pip', 'install', '--no-cache-dir', '-r', '/workspace/data-driven-design/requirements.txt'], returncode=0)

In [22]:
%pip install --no-cache-dir -r /workspace/data-driven-design/requirements.txt

Requirement already satisfied: feature-engine>=1.2.0 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 1)) (1.6.2)
Requirement already satisfied: setuptools>=70.3.0 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 2)) (75.8.2)
Requirement already satisfied: wheel>=0.45.1 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 3)) (0.45.1)
Requirement already satisfied: streamlit>=1.14.0 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 4)) (1.42.2)
Requirement already satisfied: plotly<5.17.0,>=5.16.0 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 5)) (5.16.1)
Requirement already satisfied: numpy>=1.20.0 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 6)) (2.2.3)
Requirement already satisfied: pandas>=1.5.3 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 7)) (2.2.3)
Requirement already satisfied: seaborn==0.11.2 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 8)) (0.11.2)
Requirement already satisfied: matplotlib==3.7.0 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 9)) (3.7.0)
Requirement already satisfied: scikit-learn==1.2.2 in ./.pip-modules/lib/python3.10/site-packages (from -r /workspace/data-driven-design/requirements.txt (line 10)) (1.2.2)
Requirement already satisfied: scipy>=1.0 in ./.pip-modules/lib/python3.10/site-packages (from seaborn==0.11.2->-r /workspace/data-driven-design/requirements.txt (line 8)) (1.15.2)
Requirement already satisfied: contourpy>=1.0.1 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (1.3.1)
Requirement already satisfied: cycler>=0.10 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (4.56.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (1.4.8)
Requirement already satisfied: packaging>=20.0 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (24.2)
Requirement already satisfied: pillow>=6.2.0 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in ./.pip-modules/lib/python3.10/site-packages (from matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (2.9.0.post0)
Requirement already satisfied: joblib>=1.1.1 in ./.pip-modules/lib/python3.10/site-packages (from scikit-learn==1.2.2->-r /workspace/data-driven-design/requirements.txt (line 10)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./.pip-modules/lib/python3.10/site-packages (from scikit-learn==1.2.2->-r /workspace/data-driven-design/requirements.txt (line 10)) (3.5.0)
Requirement already satisfied: statsmodels>=0.11.1 in ./.pip-modules/lib/python3.10/site-packages (from feature-engine>=1.2.0->-r /workspace/data-driven-design/requirements.txt (line 1)) (0.14.4)
Requirement already satisfied: altair<6,>=4.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (5.5.0)
Requirement already satisfied: blinker<2,>=1.0.0 in /usr/lib/python3/dist-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (1.4)
Requirement already satisfied: cachetools<6,>=4.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (5.5.2)
Requirement already satisfied: click<9,>=7.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (8.1.8)
Requirement already satisfied: protobuf<6,>=3.20 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (19.0.1)
Requirement already satisfied: requests<3,>=2.27 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (13.9.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.1.44)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in ./.pip-modules/lib/python3.10/site-packages (from streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (6.4.2)
Requirement already satisfied: pytz>=2020.1 in ./.pip-modules/lib/python3.10/site-packages (from pandas>=1.5.3->-r /workspace/data-driven-design/requirements.txt (line 7)) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in ./.pip-modules/lib/python3.10/site-packages (from pandas>=1.5.3->-r /workspace/data-driven-design/requirements.txt (line 7)) (2025.1)
Requirement already satisfied: jinja2 in ./.pip-modules/lib/python3.10/site-packages (from altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.1.5)
Requirement already satisfied: jsonschema>=3.0 in ./.pip-modules/lib/python3.10/site-packages (from altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in ./.pip-modules/lib/python3.10/site-packages (from altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (1.29.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in ./.pip-modules/lib/python3.10/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (4.0.12)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib==3.7.0->-r /workspace/data-driven-design/requirements.txt (line 9)) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.pip-modules/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in ./.pip-modules/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.pip-modules/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.pip-modules/lib/python3.10/site-packages (from requests<3,>=2.27->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2025.1.31)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.pip-modules/lib/python3.10/site-packages (from rich<14,>=10.14.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.pip-modules/lib/python3.10/site-packages (from rich<14,>=10.14.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2.19.1)
Requirement already satisfied: patsy>=0.5.6 in ./.pip-modules/lib/python3.10/site-packages (from statsmodels>=0.11.1->feature-engine>=1.2.0->-r /workspace/data-driven-design/requirements.txt (line 1)) (1.0.1)
Requirement already satisfied: smmap<6,>=3.0.1 in ./.pip-modules/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.pip-modules/lib/python3.10/site-packages (from jinja2->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in ./.pip-modules/lib/python3.10/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (25.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.pip-modules/lib/python3.10/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in ./.pip-modules/lib/python3.10/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in ./.pip-modules/lib/python3.10/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.23.1)
Requirement already satisfied: mdurl~=0.1 in ./.pip-modules/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit>=1.14.0->-r /workspace/data-driven-design/requirements.txt (line 4)) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [23]:
!pip list --format=columns

Package                   Version
------------------------- -----------
altair                    5.5.0
asttokens                 3.0.0
attrs                     25.1.0
cachetools                5.5.2
certifi                   2025.1.31
charset-normalizer        3.4.1
click                     8.1.8
comm                      0.2.2
contourpy                 1.3.1
cycler                    0.12.1
debugpy                   1.8.12
decorator                 5.2.1
exceptiongroup            1.2.2
executing                 2.2.0
feature-engine            1.6.2
fonttools                 4.56.0
gitdb                     4.0.12
GitPython                 3.1.44
idna                      3.10
ipykernel                 6.29.5
ipython                   8.33.0
jedi                      0.19.2
Jinja2                    3.1.5
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
jupyter_client            8.6.3
jupyter_core              5.7.2
kiwisolver                1.4.8
markdown-it-py            3.0.0
MarkupSafe                3.0.2
matplotlib                3.7.0
matplotlib-inline         0.1.7
mdurl                     0.1.2
narwhals                  1.29.0
nest-asyncio              1.6.0
numpy                     2.2.3
packaging                 24.2
pandas                    2.2.3
parso                     0.8.4
patsy                     1.0.1
pexpect                   4.9.0
pillow                    11.1.0
pip                       25.0.1
platformdirs              4.3.6
plotly                    5.16.1
prompt_toolkit            3.0.50
protobuf                  5.29.3
psutil                    7.0.0
ptyprocess                0.7.0
pure_eval                 0.2.3
pyarrow                   19.0.1
pydeck                    0.9.1
Pygments                  2.19.1
python-dateutil           2.9.0.post0
pytz                      2025.1
pyzmq                     26.2.1
referencing               0.36.2
requests                  2.32.3
rich                      13.9.4
rpds-py                   0.23.1
scikit-learn              1.2.2
scipy                     1.15.2
seaborn                   0.11.2
setuptools                75.8.2
smmap                     5.0.2
stack-data                0.6.3
statsmodels               0.14.4
streamlit                 1.42.2
tenacity                  9.0.0
threadpoolctl             3.5.0
toml                      0.10.2
tornado                   6.4.2
traitlets                 5.14.3
typing_extensions         4.12.2
tzdata                    2025.1
urllib3                   2.3.0
watchdog                  6.0.0
wcwidth                   0.2.13
wheel                     0.45.1

In [6]:
#pip freeze > requirements.txt

# Fetch data from Kaggle

Download data file directly from Kaggle and upload to Explorer in Git Pod workspace via local computer:

Step 1: Go to [Aircraft Performance (Aircraft Bluebook) ](https://www.kaggle.com/datasets/heitornunes/aircraft-performance-dataset-aircraft-bluebook?select=Airplane_Complete_Imputation.csv)

Step 2: Scroll down and choose the "Airplane Complete Imputation.csv"-file 

<img src="/workspace/data-driven-design/images_notebook/choose_file_from_kaggle.jpg" alt="Screenshot showing which file on Kaggle to download" width="700" />

Step 3: Download data file from Kaggle to local computer [Aircraft Performance (Aircraft Bluebook) ](https://www.kaggle.com/datasets/heitornunes/aircraft-performance-dataset-aircraft-bluebook?select=Airplane_Complete_Imputation.csv)

<img src="/workspace/data-driven-design/images_notebook/download_from_kaggle.jpg" alt="Screenshot showing where to download the data on Kaggle" width="700" />

---

# Load, Rearrange and Inspect Kaggle data

Set pandas to display all columns without truncating (and enabling horizontal slider)

In [7]:
import pandas as pd
pd.set_option('display.max_columns', None)  # Show all columns

In [8]:
df = pd.read_csv(f"inputs/datasets/raw/Airplane_Complete_Imputation.csv")
df.head()

,Model,Company,Engine Type,Multi Engine,TP mods,THR,SHP,Length,Height,Wing Span,FW,MEW,AUW,Vmax,Vcruise,Vstall,Hmax,Hmax (One),ROC,ROC (One),Vlo,Slo,Vl,Sl,Range
0,15 AC Sedan,Aeronca,Piston,False,False,NaN,145.0,25.250000,10.250000,37.416667,241.2,1180.0,2050.0,104.0,91.0,46.0,13000.0,13000.0,450.0,450.0,900.0,391.970247,1300.0,257.745075,370.0
1,11 CC Super Chief,Aeronca,Piston,False,False,NaN,85.0,20.583333,8.750000,36.083333,100.5,820.0,1350.0,89.0,83.0,44.0,12300.0,12300.0,600.0,600.0,720.0,26.247647,800.0,225.324824,190.0
2,7 CCM Champ,Aeronca,Piston,False,False,NaN,90.0,21.416667,8.583333,35.000000,127.3,810.0,1300.0,90.0,78.0,37.0,16000.0,16000.0,650.0,650.0,475.0,363.139711,850.0,585.751317,210.0
3,7 DC Champ,Aeronca,Piston,False,False,NaN,85.0,21.416667,8.583333,35.000000,127.3,800.0,1300.0,88.0,78.0,37.0,13000.0,13000.0,620.0,620.0,500.0,407.797297,850.0,642.046166,210.0
4,7 AC Champ,Aeronca,Piston,False,False,NaN,65.0,21.416667,8.750000,35.000000,93.8,740.0,1220.0,83.0,74.0,33.0,12500.0,12500.0,370.0,370.0,632.0,297.056192,885.0,329.571813,175.0

Rearrange columns in data to group features that belong together side by side in order to make heatmaps etc. more easily interpreted

In [9]:
new_order = ['Model', 'Company', 'Wing Span', 'Length', 'Height', 'Multi Engine', 'TP mods', 'Engine Type', 'THR', 'SHP', 'AUW', 'MEW', 'FW', 'Vmax', 'Vcruise', 'Vstall', 'Range', 'Hmax', 'Hmax (One)', 'ROC', 'ROC (One)', 'Vlo', 'Slo', 'Vl', 'Sl']  # Specify new order
df = df[new_order]
df.to_csv('rearranged_file.csv', index=False)  # We overwrite the df with this rearranged file
df.head()

,Model,Company,Wing Span,Length,Height,Multi Engine,TP mods,Engine Type,THR,SHP,AUW,MEW,FW,Vmax,Vcruise,Vstall,Range,Hmax,Hmax (One),ROC,ROC (One),Vlo,Slo,Vl,Sl
0,15 AC Sedan,Aeronca,37.416667,25.250000,10.250000,False,False,Piston,NaN,145.0,2050.0,1180.0,241.2,104.0,91.0,46.0,370.0,13000.0,13000.0,450.0,450.0,900.0,391.970247,1300.0,257.745075
1,11 CC Super Chief,Aeronca,36.083333,20.583333,8.750000,False,False,Piston,NaN,85.0,1350.0,820.0,100.5,89.0,83.0,44.0,190.0,12300.0,12300.0,600.0,600.0,720.0,26.247647,800.0,225.324824
2,7 CCM Champ,Aeronca,35.000000,21.416667,8.583333,False,False,Piston,NaN,90.0,1300.0,810.0,127.3,90.0,78.0,37.0,210.0,16000.0,16000.0,650.0,650.0,475.0,363.139711,850.0,585.751317
3,7 DC Champ,Aeronca,35.000000,21.416667,8.583333,False,False,Piston,NaN,85.0,1300.0,800.0,127.3,88.0,78.0,37.0,210.0,13000.0,13000.0,620.0,620.0,500.0,407.797297,850.0,642.046166
4,7 AC Champ,Aeronca,35.000000,21.416667,8.750000,False,False,Piston,NaN,65.0,1220.0,740.0,93.8,83.0,74.0,33.0,175.0,12500.0,12500.0,370.0,370.0,632.0,297.056192,885.0,329.571813

DataFrame Summary. Click 'View as a scrollable element' at the bottom of the output in case the 'display.max_columns'-command does not work (probably overruled by jupyter notebook)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 860 entries, 0 to 859
Data columns (total 25 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Model         860 non-null    object
 1   Company       860 non-null    object
 2   Wing Span     860 non-null    float64
 3   Length        860 non-null    float64
 4   Height        860 non-null    float64
 5   Multi Engine  860 non-null    bool
 6   TP mods       860 non-null    bool
 7   Engine Type   860 non-null    object
 8   THR           156 non-null    float64
 9   SHP           704 non-null    float64
 10  AUW           860 non-null    float64
 11  MEW           860 non-null    float64
 12  FW            860 non-null    float64
 13  Vmax          860 non-null    float64
 14  Vcruise       860 non-null    float64
 15  Vstall        860 non-null    float64
 16  Range         860 non-null    float64
 17  Hmax          860 non-null    float64
 18  Hmax (One)    860 non-null    float64
 19  ROC           860 non-null    float64
 20  ROC (One)     860 non-null    float64
 21  Vlo           860 non-null    float64
 22  Slo           860 non-null    float64
 23  Vl            860 non-null    float64
 24  Sl            860 non-null    float64
dtypes: bool(2), float64(20), object(3)
memory usage: 156.3+ KB

We want to check if there are duplicated airplanes by checking `Model`: There are three duplicates.

The 'keep=False' ensures that both lines of duplicate values are being displayed

In [11]:
df[df.duplicated(subset=['Model'], keep=False)]

,Model,Company,Wing Span,Length,Height,Multi Engine,TP mods,Engine Type,THR,SHP,AUW,MEW,FW,Vmax,Vcruise,Vstall,Range,Hmax,Hmax (One),ROC,ROC (One),Vlo,Slo,Vl,Sl
29,AT-602,"Air Tractor, Inc.",56.000000,33.500000,12.166667,False,False,Propjet,NaN,1050.0,12500.0,5829.0,1447.2,158.000,126.00,52.000000,600.0,8000.0,8000.000000,650.000000,650.000000,1756.907849,1830.0,1949.973315,1634.223699
65,AT-602,Beechcraft (Hawker Beechcraft),56.000000,33.500000,11.000000,False,False,Propjet,NaN,1050.0,12500.0,5829.0,1447.2,158.000,126.00,52.000000,600.0,8000.0,8000.000000,650.000000,650.000000,2803.267722,1830.0,2862.650930,1820.805987
445,Lineage 1000,Dassault Falcon Jet,94.250000,118.916667,33.750000,True,False,Jet,18500.0,NaN,120152.0,70841.0,48217.0,546.940,472.00,133.063795,4600.0,41000.0,16816.632111,2464.000000,720.000000,7351.680105,6076.0,4108.774275,2450.000000
481,Lineage 1000,Embraer Aircraft - Empresa Brasileira,94.250000,118.916667,33.750000,True,False,Jet,18500.0,NaN,120152.0,70841.0,48217.0,546.940,452.00,107.896643,4592.0,41000.0,16648.502977,2464.000000,720.000000,6661.152244,6076.0,2647.677210,3402.000000
511,G500,Gulfstream Aerospace,86.333333,91.166667,25.500000,True,False,Jet,15144.0,NaN,79600.0,46850.0,30250.0,616.975,566.95,127.868748,5300.0,51000.0,29210.904017,2467.000000,732.453021,5912.498345,5300.0,3333.022500,2620.000000
514,G500,Gulfstream Aerospace,93.500000,96.416667,25.833333,True,False,Jet,15385.0,NaN,85100.0,47600.0,34939.0,590.295,566.95,107.629085,5200.0,51000.0,27700.000000,5515.951635,707.000000,6700.448422,5150.0,4383.458188,2770.000000

The double entries having the same and almost the same values for their features probably refer to confusion in the "Company" or similar versions of the same model.  We will drop one of each double entries.

In [12]:
# Drop the row at index 1
df_dropped = df.drop(index=[65, 445, 514], inplace=True)
print(df_dropped)

None

We check for duplicates again: There are no duplicates.

In [13]:
df[df.duplicated(subset=['Model'], keep=False)]

Empty DataFrame
Columns: [Model, Company, Wing Span, Length, Height, Multi Engine, TP mods, Engine Type, THR, SHP, AUW, MEW, FW, Vmax, Vcruise, Vstall, Range, Hmax, Hmax (One), ROC, ROC (One), Vlo, Slo, Vl, Sl]
Index: []

We noticed `Engine Type` is a categorical variable with three alternatives: 'Piston', 'Propjet'and 'Jet'. We will replace/convert the categories to integers as the ML model requires numeric variables.

In [14]:
df['Engine Type'].unique()

array(['Piston', 'Propjet', 'Jet'], dtype=object)

In [15]:
df['Engine Type'] = df['Engine Type'].replace({"Piston":0, "Propjet":1, "Jet":2})

Check the `Engine Type` data type.

In [16]:
df['Engine Type'].dtype

dtype('int64')

Finally before we push the df to the repo we replace the pesky spaces with underscores.

In [17]:
# Renaming columns
df.rename(columns={
    'Multi Engine': 'Multi_Engine',
    'Wing Span': 'Wing_Span',
    'TP mods': 'TP_mods',  # Fixed this entry to match naming convention
    'Engine Type': 'Engine_Type',  # Adjusted to use underscores
    'Hmax (One)': 'Hmax_(One)',
    'ROC (One)': 'ROC_(One)'
}, inplace=True)

# Push files to Repo

In [18]:
import os
try:
  os.makedirs(name='outputs/datasets/collection') # create outputs/datasets/collection folder
except Exception as e:
  print(e)

df.to_csv(f"outputs/datasets/collection/airplane_performance_study.csv",index=False)

[Errno 17] File exists: 'outputs/datasets/collection'

Double check that we really have the correct update csv-file in the repo and yes it is correct.

In [19]:
df = pd.read_csv(f"outputs/datasets/collection/airplane_performance_study.csv")
df.head()

,Model,Company,Wing_Span,Length,Height,Multi_Engine,TP_mods,Engine_Type,THR,SHP,AUW,MEW,FW,Vmax,Vcruise,Vstall,Range,Hmax,Hmax_(One),ROC,ROC_(One),Vlo,Slo,Vl,Sl
0,15 AC Sedan,Aeronca,37.416667,25.250000,10.250000,False,False,0,NaN,145.0,2050.0,1180.0,241.2,104.0,91.0,46.0,370.0,13000.0,13000.0,450.0,450.0,900.0,391.970247,1300.0,257.745075
1,11 CC Super Chief,Aeronca,36.083333,20.583333,8.750000,False,False,0,NaN,85.0,1350.0,820.0,100.5,89.0,83.0,44.0,190.0,12300.0,12300.0,600.0,600.0,720.0,26.247647,800.0,225.324824
2,7 CCM Champ,Aeronca,35.000000,21.416667,8.583333,False,False,0,NaN,90.0,1300.0,810.0,127.3,90.0,78.0,37.0,210.0,16000.0,16000.0,650.0,650.0,475.0,363.139711,850.0,585.751317
3,7 DC Champ,Aeronca,35.000000,21.416667,8.583333,False,False,0,NaN,85.0,1300.0,800.0,127.3,88.0,78.0,37.0,210.0,13000.0,13000.0,620.0,620.0,500.0,407.797297,850.0,642.046166
4,7 AC Champ,Aeronca,35.000000,21.416667,8.750000,False,False,0,NaN,65.0,1220.0,740.0,93.8,83.0,74.0,33.0,175.0,12500.0,12500.0,370.0,370.0,632.0,297.056192,885.0,329.571813